### ISSUE TITLE
Can't find TobiiGazeCore32.dll

### ISSUE THREAD

**Issue by Lehis** [MastaLomaster/bkb#6]
Hi, 
Thanks for the program! I cannot find neither TobiiGazeCore32.dll nor TobiiGazeCore64.dll anyware even after the  installution of http://files.update.tech.tobii.com/engine/Tobii.EyeX_2.1.1.293.exe.

**Comment by MastaLomaster** [comment]
HI,

You don't need the TobiiGazeConfig32.dll file, you need the
TobiiGazeCore32.dll one.

The config dll was used in the very old version.

Regards,
Mikhail.

Пн, 27 нояб. 2017 г. в 21:29, Lehis <notifications@github.com>:

**Comment by Lehis** [comment]
Yes, I mean TobiiGazeCore32.dll :)

**Comment by MastaLomaster** [comment]
What operating system do you use? I will try to reproduce.

**Comment by Lehis** [comment]
Windows 7 x64, SP1.
Thank you in advance!

**Comment by MastaLomaster** [comment]
Just installed the Tobii.EyeX_2.1.1.293 on a fresh Windows 7 64-bit SP1 machine.
The file is located in "C:\Program Files (x86)\Tobii\Tobii EyeX"
![tobiigazecore32](https://user-images.githubusercontent.com/6312547/33284625-c2c5aaea-d3c0-11e7-9999-b3eabba0242e.png)

**Comment by Lehis** [comment]
![tobii](https://user-images.githubusercontent.com/25395278/33284831-f472f472-d3e2-11e7-90d2-bf2374a18055.png)

**Comment by Lehis** [comment]
I found the problem!
We have to install Tobii.EyeX_2.1.1.293 without installution the latest Tobii Eye Tracking Core Software v2.11 form the official website. But in thi way Tobii Eye Tracker 4C device cannot be initialized.

**Comment by MastaLomaster** [comment]
Ну, поставьте сначала Tobii.EyeX_2.1.1.293, а потом уж Tobii Eye Tracking Core Software v2.11.
Или выцарапайте файл TobiiGazeCore32.dll, потом снесите Tobii.EyeX_2.1.1.293 и установите Tobii Eye Tracking Core Software v2.11.

**Comment by Lehis** [comment]
Solved!
The sequence can be as follows:
1. Do not install official software for Tobii Eye Tracker 4C, just the driver.
2. Find  TobiiGazeCore32.dll in C:\Program Files (x86)\Tobii\Tobii EyeX\ and copy it
3. Install the official software for Tobii Eye Tracker 4C and initialize the device
4. Copy  TobiiGazeCore32.dll to the folder with bkb32d.exe

**Comment by MastaLomaster** [comment]
TobiiGazeCore32.dll is not used in the program anymore (since Revision F). Closed.
